import { Role } from '../enums';
import type { GetUserBasicDTO, GetUserBasicDTOKeysetPaginationResult } from '../interface';

// Фейковые данные для разработки
export const mockUsers: GetUserBasicDTO[] = [
  {
    id: '1',
    email: 'admin@compass.local',
    role: Role.Admin,
    phoneNumber: '+996 555 123 456',
    fullName: 'Администратор Системы',
    avatarUrl: '/logo/LogoSmallBig.png',
    online: true,
  },
  {
    id: '2',
    email: 'operator@compass.local',
    role: Role.Operator,
    phoneNumber: '+996 555 234 567',
    fullName: 'Оператор Иванов',
    avatarUrl: null,
    online: true,
  },
  {
    id: '3',
    email: 'driver1@compass.local',
    role: Role.Driver,
    phoneNumber: '+996 555 345 678',
    fullName: 'Алексей Петров',
    avatarUrl: null,
    online: true,
  },
  {
    id: '4',
    email: 'driver2@compass.local',
    role: Role.Driver,
    phoneNumber: '+996 555 456 789',
    fullName: 'Михаил Сидоров',
    avatarUrl: null,
    online: false,
  },
  {
    id: '5',
    email: 'customer1@example.com',
    role: Role.Customer,
    phoneNumber: '+996 555 567 890',
    fullName: 'Анна Козлова',
    avatarUrl: null,
    online: false,
  },
  {
    id: '6',
    email: 'partner@compass.local',
    role: Role.Partner,
    phoneNumber: '+996 555 678 901',
    fullName: 'Партнер ООО "Такси"',
    avatarUrl: null,
    online: true,
  },
  {
    id: '7',
    email: 'terminal1@compass.local',
    role: Role.Terminal,
    phoneNumber: null,
    fullName: 'Терминал Аэропорт',
    avatarUrl: null,
    online: true,
  },
  {
    id: '8',
    email: 'customer2@example.com',
    role: Role.Customer,
    phoneNumber: '+996 555 789 012',
    fullName: 'Дмитрий Волков',
    avatarUrl: null,
    online: false,
  },
  {
    id: '9',
    email: 'driver3@compass.local',
    role: Role.Driver,
    phoneNumber: '+996 555 890 123',
    fullName: 'Сергей Морозов',
    avatarUrl: null,
    online: true,
  },
  {
    id: '10',
    email: 'operator2@compass.local',
    role: Role.Operator,
    phoneNumber: '+996 555 901 234',
    fullName: 'Елена Смирнова',
    avatarUrl: null,
    online: false,
  },
];

export const mockUserResponse: GetUserBasicDTOKeysetPaginationResult = {
  data: mockUsers,
  totalCount: mockUsers.length,
  pageSize: 10,
  hasPrevious: false,
  hasNext: false,
};
